FROM python:3.12

ARG APP=/usr/src/app

EXPOSE 8080

ENV TZ=Etc/UTC \
  APP_USER=appuser

RUN groupadd $APP_USER \
  && useradd -g $APP_USER $APP_USER

COPY ./recommender/ $APP
WORKDIR ${APP}
RUN pip install -r requirements.txt
RUN chown -R $APP_USER:$APP_USER ${APP}
USER $APP_USER

CMD ["python", "server.py"]
