# build server
FROM rust as server-builder


RUN cargo new --bin dungeon-build
WORKDIR /dungeon-build
COPY ./server/Cargo.toml ./server/Cargo.toml
COPY ./server/src ./server/src
WORKDIR ./server
RUN cargo build --release

# configure and run app
FROM ubuntu:24.10

ARG APP=/usr/src/app

EXPOSE 80

ENV TZ=Etc/UTC \
  APP_USER=appuser

RUN groupadd $APP_USER \
  && useradd -g $APP_USER $APP_USER

COPY --from=server-builder /dungeon-build/server/target/release/server ${APP}/server
COPY ./db/init.sql ${APP}
COPY ./server/static ${APP}/static

RUN chown -R $APP_USER:$APP_USER ${APP}

USER $APP_USER
WORKDIR ${APP}

ENV STATIC_PAT=${APP}/static
ENV DB_INIT_PATH=${APP}/init.sql

CMD ["./server"]
