services:
  web:
    container_name: board4you-server
    build: .
    restart: always
    command: ./server 
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: "dungeon"
    ports:
      - "3000:3000"
    secrets:
      - db_password
      - jwt_secret
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: board4you-db
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: "dungeon"
      POSTGRES_PASSWORD_FILE: "/run/secrets/db_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    secrets:
      - db_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dungeon -d dungeon"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

secrets:
  db_password:
    file: ./db/db_password.txt
  jwt_secret:
    file: ./db/jwt_secret.txt
